version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Root!255724'
      MYSQL_DATABASE: 'db_library'
      MYSQL_USER: 'Veneberg'
      MYSQL_PASSWORD: 'Veneberg!255724'
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  redis:
    image: redis:latest

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    command: bash -c "sleep 15 && python manage.py collectstatic --noinput
      && python manage.py makemigrations
      && python manage.py migrate      
      && python manage.py fillusers
      && python manage.py fillbooks      
      && gunicorn library_management.wsgi -b 0.0.0.0:8080"
    depends_on:
      - db
      - redis
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend